# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c2c4509e3edbda249d0f4236243296117141bcd3215a279d46874be46b8f3dc2a1a307ad43b5a3552b0931f22cace15f59fb006b45f76f48a44f4a5f45e0f03

test:
  secret_key_base: beb7fa3efff608739b245841e86a3aa3b80674f5758f4aba676f3bd2de774689e43709206492c5705c26571704bf21a11a0a68c582301ac6e417c19e0235d6eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
